### ISSUE TITLE
ISO Image

### ISSUE THREAD

**Issue by catalinalb** [bastibl/instant-gnuradio#30]
Hello,

Can we get some more support for creating a ISO image that would run from a USB stick? 
VM is great but still slow so I would like to run it directly from usb stick. 

Thank you,
Catalin

**Comment by bastibl** [comment]
Who is _we_? There are some instructions at:
https://www.bastibl.net/instant-gnuradio/

When  you want to use it on a bootable USB drive, you might want to delete the `.git` and `build` folders to save space. Also, if you use a Casper filesystem overlay, it might take quite some time to boot, because the SDR stuff is installed in the home directory. If that's an issue, install to `/usr/`
